baseURL = "http://wampsharp.net"
languageCode = "en-us"
title = "WampSharp"

[params]
description = "A C# implementation of WAMP (The Web Application Messaging Protocol)"
copyright    = "Copyright (c) 2013-2017, Elad Zelingher; All rights reserved."
analytics = "UA-98663639-2"